### ISSUE TITLE
Adding Teammates

### ISSUE THREAD

**Issue by HockeyGuy1985** [HadenHiles/TenThousandShotChallenge#17]
The ability to add/invite friends to the Team Challenge (as opposed to having them join themselves with the code).

**Comment by HadenHiles** [comment]
We did think about this but couldn't justify the additional time it would require for the latest update. Sharing a screenshot of the team's code or QR code seems like a good middle ground to get the job done 😅

Closing for now but will keep in mind for future updates if enough people request it.
